[project]
name = 'Blockchain-Based-Retail-Inventory-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.shrinkage-monitoring]
path = 'contracts/shrinkage-monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.supplier-verification]
path = 'contracts/supplier-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
